//서버 프로토콜
export const ENV_PROTOCOL_KEY = 'PROTOCOL';
//서버 호스트->localhost:3000
export const ENV_HOST_KEY = 'HOST';
//JWT 토큰 시크릿
export const ENV_JWT_SECRET_KEY = 'JWT_SECRET';
export const ENV_HASH_ROUNDS_KEY = 'HASH_ROUNDS';

//postgres db설정
export const ENV_POSTGRES_DB_HOST_KEY = 'POSTGRES_DB_HOST';
export const ENV_POSTGRES_DB_PORT_KEY = 'POSTGRES_DB_PORT';
export const ENV_POSTGRES_DB_USERNAME_KEY = 'POSTGRES_DB_USERNAME';
export const ENV_POSTGRES_DB_DATABASE_KEY = 'POSTGRES_DB_DATABASE';
export const ENV_POSTGRES_DB_PASSWORD_KEY = 'POSTGRES_DB_PASSWORD';

//mongodb 설정
export const ENV_MONGO_DB_HOST_KEY = 'MONGO_DB_HOST';
export const ENV_MONGO_DB_PORT_KEY = 'MONGO_DB_PORT';
export const ENV_MONGO_DB_DATABASE_KEY = 'MONGO_DB_DATABASE';
export const ENV_MONGO_DB_AUTHSOURCE_KEY = 'MONGO_DB_AUTHSOURCE';
export const ENV_MONGO_DB_USER_KEY = 'MONGO_DB_USER';
export const ENV_MONGO_DB_PASSWORD_KEY = 'MONGO_DB_PASSWORD';
