version: '3.1'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
